language: csharp
os:
  - linux
  - osx
mono:
  - latest
solution: Avalonia.travis-mono.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gtk-sharp2 ; fi
  - mono .nuget/nuget.exe restore Avalonia.travis-mono.sln
  - mono .nuget/nuget.exe install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Avalonia.travis-mono.sln
  - ./tests/run-tests.sh
  - mono ./packages/JetBrains.dotMemoryUnit.2.1.20150828.125449/tools/dotMemoryUnit.exe -targetExecutable="./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe" -returnTargetExitCode  --"tests/Avalonia.LeakTests/bin/Release/Avalonia.LeakTests.dll"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/98f653320ef2b7506c05
    on_success: change
    on_failure: always
    on_start: never
