version: 1.0.{build}
os: Visual Studio 2015
before_build:
- git submodule update --init
- nuget restore Perspex.sln

environment:
  myget_key:
    secure: XOgD5bJUKNOS2kDDgb+affS4pDcslxALh+xvvnr1Koy0PjXlhILsBdNhxRe0KcNm

install:
- appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
- start /wait msiexec /i gtk-sharp-2.12.26.msi /qn /norestart

configuration:
  - Release

after_test:
- ps: nuget\build-appveyor.ps1

artifacts:
  - path: nuget\*.nupkg

build:
  project: Perspex.sln
  verbosity: minimal
