version: 1.0.{build}
os: Visual Studio 2015
before_build:
- git submodule update --init
- nuget restore Perspex.sln


configuration:
  - Release

after_build:
- ps: nuget\build-appveyor.ps1

artifacts:
  - path: nuget\*.nupkg

build:
  project: Perspex.sln
  verbosity: minimal